version: '3.1'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 8888:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - parana-medio

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    environment:
      TZ: America/Argentina/Buenos_Aires
      PUID: ${UID:-1000}
      PGID: ${GID:-1000} 
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
    networks:
      - parana-medio 

networks:
  parana-medio:
    external: true

