version: '3.1'

services:

  db:
    image: mariadb:10.9.6
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    command: 
      --default-authentication-plugin=mysql_native_password
      --skip-log-bin
      --default-time-zone=-03:00
      --expire_logs_days=10
      --sql_mode=""
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci
      --innodb_buffer_pool_size=512M
      --innodb_log_file_size=64M
      --query_cache_type=0
      --query_cache_size=0
      --query_cache_limit=8M
      --thread_cache_size=30
      --performance_schema=ON
      --event_scheduler=ON

    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_PWD=$MYSQL_ROOT_PASSWORD
      - TZ=America/Argentina/Buenos_Aires

    volumes:
      - ./data:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf/mariadb.cnf:/etc/mysql/my.cnf:Z
      - ./logs:/var/log/mysql:Z
    networks:
      - fluxa-network  

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8181:80"
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 100000000
    networks:
      - fluxa-network 

networks:
  fluxa-network:
    external: true
